[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix client --include=dev",
  "npm install --prefix server"
]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "npm run start --prefix server"
